package com.kushagra.reconx.reports

import com.kushagra.reconx.utils.Constants

/**
 * MarkdownReportBuilder.kt
 * =========================
 * Builds a Markdown (and, by re-using the same structure, a plain-TXT)
 * research report -- the mobile port of the desktop app's
 * core/exporter.py :: export_markdown.
 */
object MarkdownReportBuilder {

    fun build(data: ReportData): String {
        val sb = StringBuilder()
        sb.appendLine("# ${Constants.APP_NAME} -- Research Report")
        sb.appendLine("*${Constants.APP_MOTTO}*")
        sb.appendLine()
        sb.appendLine("**Project:** ${data.projectName}")
        sb.appendLine("**Analyst:** ${data.analystName}")
        sb.appendLine("**Generated on:** ${data.generatedOn}")
        sb.appendLine("**Domain:** ${data.domain.ifBlank { "-" }}  |  **Entity:** ${data.entity.ifBlank { "-" }}  |  **Keyword:** ${data.keyword.ifBlank { "-" }}")
        sb.appendLine()

        if (data.description.isNotBlank()) {
            sb.appendLine("## Overview")
            sb.appendLine(data.description)
            sb.appendLine()
        }

        if (data.findingsSummary.isNotBlank()) {
            sb.appendLine("## Findings Summary")
            sb.appendLine(data.findingsSummary)
            sb.appendLine()
        }

        if (data.queries.isNotEmpty()) {
            sb.appendLine("## Saved Queries")
            data.queries.groupBy { it.category }.forEach { (category, items) ->
                sb.appendLine("### $category")
                items.forEach { q ->
                    sb.appendLine("- **[${q.engine}] ${q.title}**")
                    sb.appendLine("  ```")
                    sb.appendLine("  ${q.query}")
                    sb.appendLine("  ```")
                }
                sb.appendLine()
            }
        }

        if (data.notes.isNotEmpty()) {
            sb.appendLine("## Research Notes")
            data.notes.forEach { n ->
                sb.appendLine("### ${n.title} _(${n.createdAt})_")
                sb.appendLine(n.content)
                sb.appendLine()
            }
        }

        sb.appendLine("---")
        sb.appendLine("Report generated by ${Constants.APP_NAME}.")
        return sb.toString()
    }

    /** A plain-text variant: same content, no Markdown syntax. */
    fun buildPlainText(data: ReportData): String =
        build(data)
            .replace(Regex("^#+\\s*", RegexOption.MULTILINE), "")
            .replace("```", "")
            .replace("**", "")
            .replace("*", "")
}
